hash = "sha256-iP5NE0FtcWe924MYWvgG7cg00Y2uyboB57YfrGkrig0="
[cargoHash]
ukvm = "sha256-Bh7cgTUBPzyfzQGreLOUaoMX3OwFsTIJfIgxVxV5ke0="
ukvms = "sha256-Bh7cgTUBPzyfzQGreLOUaoMX3OwFsTIJfIgxVxV5ke0="
ukvmc = "sha256-Bh7cgTUBPzyfzQGreLOUaoMX3OwFsTIJfIgxVxV5ke0="
