hash = "sha256-iP5NE0FtcWe924MYWvgG7cg00Y2uyboB57YfrGkrig0="
[cargoHash]
ukvm = "sha256-82zE+fP04j1m+ID8EKK4p5dwg5y6pIhjM0c06YlHQ2U="
ukvms = "sha256-NThSJkz/kjLQgBl/00tnOhVV4xWdjXZuML+bCzOHGXA="
ukvmc = "sha256-l8QRbhVGFICNQKc5Pn94zWOyCMr43X6LwNuWoF4582w="
