["1.2.3"]
hash = "sha256-7T6xdJrVTgg7rSTC2PaVTsBTgi14qJzaR6M8tRUL8OQ="
cargoHash = "sha256-9wAGUVYKz7+Q8y+dmay8pEZnv7PikzuAoas/h5T3sLE="
["2.2.1"]
hash = "sha256-xRZ7Pz9sK/YzYB9wH5yYKB9Jgd91ci3NSSy/85HYJMg="
cargoHash = "sha256-W3DfWsRxfL94N21wEX2yhaU9YLPJqylsSt4ZSDnJgwc="
